import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Felicia Chang</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <div>present</div>
          <div>
            Collecting feelings on offandco · Writing on two pages double spaced
            · Looking for a job as a creative technologist / frontend
            developer...
          </div>
          <div>past</div>
          <div>
            Built a search result using large language models at neeva · Served
            rich recipe and shopping results at neeva · Made poetry interactive
            on readalibi · Only observed on only observations · Freelanced for
            the yale politic · Creatively embedded systems for lux et veritas ·
          </div>
        </div>
        <div>
          <div>present</div>
          <div>
            Collecting feelings on offandco · Writing on two pages double spaced
            · Looking for a job as a creative technologist / frontend
            developer...
          </div>
          <div>past</div>
          <div>
            Built a search result using large language models at neeva · Served
            rich recipe and shopping results at neeva · Made poetry interactive
            on readalibi · Only observed on only observations · Freelanced for
            the yale politic · Creatively embedded systems for lux et veritas ·
          </div>
        </div>
      </main>
    </>
  );
}
